# Generated by Django 2.2.8 on 2019-12-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_subcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='sub_slug',
        ),
    ]
