# Generated by Django 2.2.8 on 2019-12-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0003_auto_20191230_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
