# Generated by Django 3.0.5 on 2020-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0004_subcategory_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
