# Generated by Django 2.2.8 on 2019-12-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191227_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
