# Generated by Django 2.2.8 on 2019-12-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191230_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_pic',
            field=models.ImageField(upload_to='news_pics'),
        ),
    ]
